name: wize_budge
description: "WizeBudge - Smart Financial Management App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_slidable: ^4.0.3
  shimmer: ^3.0.0
  hugeicons: ^1.1.1
  google_generative_ai: ^0.4.7
  pdf: ^3.10.8
  path_provider: ^2.1.2
  in_app_purchase: ^3.1.13
  share_plus: ^12.0.1
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  device_info_plus: ^12.2.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.41
  local_auth_darwin: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/WizeBudge Icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/WizeBudge Icon.png"
    background_color: "#6366F1"
    theme_color: "#6366F1"
  windows:
    generate: true
    image_path: "assets/images/WizeBudge Icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/WizeBudge Icon.png"
