// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmmvE06rTbEF-nqdxrijJGfK2f0HFyWHY',
    appId: '1:701898587584:web:d071fb2233f0e240e6dc25',
    messagingSenderId: '701898587584',
    projectId: 'wize-budge',
    authDomain: 'wize-budge.firebaseapp.com',
    storageBucket: 'wize-budge.firebasestorage.app',
    measurementId: 'G-TQKG0SK3N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_5UBYAOHp3QUZESRxvPO_7rE8y4pSM4',
    appId: '1:701898587584:android:335add83c8df0835e6dc25',
    messagingSenderId: '701898587584',
    projectId: 'wize-budge',
    storageBucket: 'wize-budge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxmKhvuxV1LnATtegWB0gs7XGqqSTUOBY',
    appId: '1:701898587584:ios:2ecf3cb1be09532ce6dc25',
    messagingSenderId: '701898587584',
    projectId: 'wize-budge',
    storageBucket: 'wize-budge.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );
}
